const XLSX = require('xlsx');

const data = [
  ['Priorité', 'Catégorie', 'Média', 'Site web', 'Contact (à trouver)'],
  [1,  'National Tier 1', 'CNN', 'https://www.cnn.com', ''],
  [2,  'National Tier 1', 'NPR', 'https://www.npr.org', ''],
  [3,  'National Tier 1', 'Forbes', 'https://www.forbes.com', ''],
  [4,  'National Tier 1', 'TIME', 'https://time.com', ''],
  [5,  'National Tier 1', 'HuffPost', 'https://www.huffpost.com', ''],
  [6,  'National Tier 1', 'Business Insider', 'https://www.businessinsider.com', ''],
  [7,  'National Tier 1', 'US News & World Report', 'https://www.usnews.com', ''],
  [8,  'National Tier 1', 'Vogue', 'https://www.vogue.com', ''],
  [9,  'National Tier 1', 'Elle', 'https://www.elle.com', ''],
  [10, 'National Tier 1', 'Glamour', 'https://www.glamour.com', ''],
  [11, 'National Tier 1', 'Allure', 'https://www.allure.com', ''],
  [12, 'National Tier 1', 'Vanity Fair', 'https://www.vanityfair.com', ''],
  [13, 'National Tier 1', 'Good Housekeeping', 'https://www.goodhousekeeping.com', ''],
  [14, 'National Tier 1', 'The Verge', 'https://www.theverge.com', ''],
  [15, 'National Tier 2', 'WebMD', 'https://www.webmd.com', ''],
  [16, 'National Tier 2', 'Everyday Health', 'https://www.everydayhealth.com', ''],
  [17, 'National Tier 2', 'PBS NewsHour', 'https://www.pbs.org/newshour', ''],
  [18, 'National Tier 2', 'Vice', 'https://www.vice.com', ''],
  [19, 'National Tier 2', 'Refinery29', 'https://www.refinery29.com', ''],
  [20, 'National Tier 2', 'PureWow', 'https://www.purewow.com', ''],
  [21, 'National Tier 2', 'Apartment Therapy', 'https://www.apartmenttherapy.com', ''],
  [22, 'National Tier 2', 'Saveur', 'https://www.saveur.com', ''],
  [23, 'National Tier 2', 'MedPage Today', 'https://www.medpagetoday.com', ''],
  [24, 'National Tier 2', 'Modern Healthcare', 'https://www.modernhealthcare.com', ''],
  [25, 'National Tier 2', "Nation's Restaurant News", 'https://www.nrn.com', ''],
  [26, 'National Tier 2', 'New Hope Network', 'https://www.newhope.com', ''],
  [27, 'National Tier 2', 'Semafor', 'https://www.semafor.com', ''],
  [28, 'National Tier 2', 'The Hill', 'https://thehill.com', ''],
  [29, 'National Tier 2', 'mindbodygreen', 'https://www.mindbodygreen.com', ''],
  [30, 'National Tier 2', 'SELF', 'https://www.self.com', ''],
  [31, 'National Tier 2', "Women's Health", 'https://www.womenshealthmag.com', ''],
  [32, 'National Tier 2', 'Prevention', 'https://www.prevention.com', ''],
  [33, 'National Tier 2', 'Delish', 'https://www.delish.com', ''],
  [34, 'National Tier 2', 'The Kitchn', 'https://www.thekitchn.com', ''],
  [35, 'TV Locale', 'KTRK-TV (ABC Houston)', 'https://abc13.com', ''],
  [36, 'TV Locale', 'KHOU (CBS Houston)', 'https://www.khou.com', ''],
  [37, 'TV Locale', 'WJLA (ABC DC)', 'https://wjla.com', ''],
  [38, 'TV Locale', 'WRAL (CBS Raleigh)', 'https://www.wral.com', ''],
  [39, 'TV Locale', 'WMAQ (NBC Chicago)', 'https://www.nbcchicago.com', ''],
  [40, 'TV Locale', 'WCAU (NBC Philly)', 'https://www.nbcphiladelphia.com', ''],
  [41, 'TV Locale', 'WBTS (NBC Boston)', 'https://www.nbcboston.com', ''],
  [42, 'TV Locale', 'WRC (NBC DC)', 'https://www.nbcwashington.com', ''],
  [43, 'TV Locale', 'KNSD (NBC San Diego)', 'https://www.nbcsandiego.com', ''],
  [44, 'TV Locale', 'KING-TV (NBC Seattle)', 'https://www.king5.com', ''],
  [45, 'TV Locale', 'KXAN (NBC Austin)', 'https://www.kxan.com', ''],
  [46, 'TV Locale', 'WSVN (Fox Miami)', 'https://wsvn.com', ''],
  [47, 'TV Locale', 'WAGA (Fox Atlanta)', 'https://www.fox5atlanta.com', ''],
  [48, 'TV Locale', 'WFLD (Fox Chicago)', 'https://www.fox32chicago.com', ''],
  [49, 'Radio Publique', 'KQED San Francisco', 'https://www.kqed.org', ''],
  [50, 'Radio Publique', 'WBEZ Chicago', 'https://www.wbez.org', ''],
  [51, 'Radio Publique', 'WBUR Boston', 'https://www.wbur.org', ''],
  [52, 'Radio Publique', 'WAMU Washington DC', 'https://www.wamu.org', ''],
  [53, 'Radio Publique', 'KUT Austin', 'https://www.kut.org', ''],
  [54, 'Radio Publique', 'KUOW Seattle', 'https://www.kuow.org', ''],
  [55, 'Radio Publique', 'WLRN Miami', 'https://www.wlrn.org', ''],
  [56, 'Radio Publique', 'WESA Pittsburgh', 'https://www.wesa.fm', ''],
  [57, 'Radio Publique', 'KERA Dallas', 'https://www.kera.org', ''],
  [58, 'Presse Régionale', 'Seattle Times', 'https://www.seattletimes.com', ''],
  [59, 'Presse Régionale', 'Denver Post', 'https://www.denverpost.com', ''],
  [60, 'Presse Régionale', 'Tampa Bay Times', 'https://www.tampabay.com', ''],
  [61, 'Presse Régionale', 'Charlotte Observer', 'https://www.charlotteobserver.com', ''],
  [62, 'Presse Régionale', 'Baltimore Sun', 'https://www.baltimoresun.com', ''],
  [63, 'Presse Régionale', 'Sacramento Bee', 'https://www.sacbee.com', ''],
  [64, 'Presse Régionale', 'The Mercury News', 'https://www.mercurynews.com', ''],
  [65, 'Presse Régionale', 'The News & Observer (Raleigh)', 'https://www.newsobserver.com', ''],
  [66, 'Presse Régionale', 'Las Vegas Review-Journal', 'https://www.reviewjournal.com', ''],
  [67, 'Presse Régionale', 'Star Tribune (Minneapolis)', 'https://www.startribune.com', ''],
  [68, 'Presse Régionale', 'The Kansas City Star', 'https://www.kansascity.com', ''],
  [69, 'Presse Régionale', 'St. Louis Post-Dispatch', 'https://www.stltoday.com', ''],
  [70, 'Presse Régionale', 'Honolulu Star-Advertiser', 'https://www.staradvertiser.com', ''],
  [71, 'Presse Régionale', "The Oregonian", 'https://www.oregonlive.com', ''],
  [72, 'Presse Régionale', 'Anchorage Daily News', 'https://www.adn.com', ''],
  [73, 'Presse Régionale', 'The Arizona Republic', 'https://www.azcentral.com', ''],
  [74, 'Presse Régionale', 'Arizona Daily Star', 'https://tucson.com', ''],
  [75, 'Presse Régionale', 'Albuquerque Journal', 'https://www.abqjournal.com', ''],
  [76, 'Presse Régionale', 'The Salt Lake Tribune', 'https://www.sltrib.com', ''],
  [77, 'Presse Régionale', 'Deseret News', 'https://www.deseret.com', ''],
  [78, 'Presse Régionale', 'Billings Gazette', 'https://billingsgazette.com', ''],
  [79, 'Presse Régionale', 'Wyoming Tribune Eagle', 'https://www.wyomingnews.com', ''],
  [80, 'Presse Régionale', 'Bismarck Tribune', 'https://bismarcktribune.com', ''],
  [81, 'Presse Régionale', 'Richmond Times-Dispatch', 'https://richmond.com', ''],
  [82, 'Presse Régionale', 'Hartford Courant', 'https://www.courant.com', ''],
  [83, 'Presse Régionale', 'Post and Courier (Charleston SC)', 'https://www.postandcourier.com', ''],
  [84, 'Presse Régionale', 'West Virginia Gazette-Mail', 'https://www.wvgazettemail.com', ''],
  [85, 'Presse Régionale', 'Arkansas Democrat-Gazette', 'https://www.arkansasonline.com', ''],
  [86, 'Presse Régionale', 'Fort Worth Star-Telegram', 'https://www.star-telegram.com', ''],
  [87, 'Magazine Régional', 'Washingtonian', 'https://www.washingtonian.com', ''],
  [88, 'Magazine Régional', 'Chicago Magazine', 'https://www.chicagomag.com', ''],
  [89, 'Magazine Régional', 'Indianapolis Monthly', 'https://www.indianapolismonthly.com', ''],
  [90, 'Magazine Régional', 'Madison Magazine', 'https://www.madisonmagazine.com', ''],
  [91, 'Magazine Régional', 'Mpls.St.Paul Magazine', 'https://www.mspmag.com', ''],
  [92, 'Magazine Régional', 'Salt Lake Magazine', 'https://www.saltlakemagazine.com', ''],
  [93, 'Magazine Régional', 'Nashville Scene', 'https://www.nashvillescene.com', ''],
  [94, 'Magazine Régional', 'Seven Days (Vermont)', 'https://www.sevendaysvt.com', ''],
  [95, 'Magazine Régional', 'Jackson Hole News & Guide', 'https://www.jhnewsandguide.com', ''],
  [96, 'Magazine Régional', 'Charleston Magazine', 'https://www.charlestonmag.com', ''],
  [97, 'Magazine Régional', 'Rhode Island Monthly', 'https://www.rimonthly.com', ''],
  [98, 'Magazine Régional', 'Cleveland Magazine', 'https://www.clevelandmagazine.com', ''],
  [99, 'Magazine Régional', 'Cincinnati Magazine', 'https://www.cincinnatimagazine.com', ''],
  [100, 'Magazine Régional', 'Feast Magazine (St. Louis)', 'https://www.feastmagazine.com', ''],
  [101, 'Magazine Régional', 'Connecticut Post', 'https://www.ctpost.com', ''],
  [102, 'Magazine Régional', 'New Hampshire Union Leader', 'https://www.unionleader.com', ''],
  [103, 'Magazine Régional', 'The State (Columbia SC)', 'https://www.thestate.com', ''],
  [104, 'Food Niche', 'The Infatuation', 'https://www.theinfatuation.com', ''],
  [105, 'Food Niche', 'Goop', 'https://goop.com', ''],
  [106, 'Food Niche', 'Cherry Bombe', 'https://cherrybombe.com', ''],
  [107, 'Food Niche', 'SF Weekly', 'https://www.sfweekly.com', ''],
  [108, 'Food Niche', 'KCRW (Good Food)', 'https://www.kcrw.com', ''],
  [109, 'Food Niche', 'LAist', 'https://laist.com', ''],
  [110, 'Food Niche', 'Edible Boston', 'https://www.edibleboston.com', ''],
  [111, 'Food Niche', 'Edible Los Angeles', 'https://www.ediblela.com', ''],
  [112, 'Food Niche', 'Taste Cooking', 'https://www.tastecooking.com', ''],
  [113, 'Food Niche', 'mindbodygreen', 'https://www.mindbodygreen.com', ''],
  [114, 'Food Niche', 'New Hope Network', 'https://www.newhope.com', ''],
];

const ws = XLSX.utils.aoa_to_sheet(data);

ws['!cols'] = [
  { wch: 10 },
  { wch: 20 },
  { wch: 35 },
  { wch: 42 },
  { wch: 38 },
];

// Make URLs in column D (index 3) clickable hyperlinks
const range = XLSX.utils.decode_range(ws['!ref']);
for (let R = 1; R <= range.e.r; R++) {
  const cellAddr = XLSX.utils.encode_cell({ r: R, c: 3 });
  const cell = ws[cellAddr];
  if (cell && cell.v && typeof cell.v === 'string' && cell.v.startsWith('http')) {
    cell.l = { Target: cell.v };
  }
}

const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, 'Médias manquants');

const outPath = 'scripts/output/medias-manquants.xlsx';
XLSX.writeFile(wb, outPath);
console.log('Fichier créé :', outPath);
